language: node_js
jobs:
  include:
  - dist: focal
    node_js: '21'
  - dist: focal
    node_js: '20'
  - dist: focal
    node_js: '18'
  - node_js: '16'
  - node_js: '14'
services:
  - redis-server
