name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    types: ['opened', 'reopened', 'synchronize']

jobs:
  test:
    strategy:
      matrix:
        nodejs: [ '20', '22', '23' ]
        redis-version: [4, 5, 6, 7]
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
      pull-requests: write
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.11.0
      with:
        access_token: ${{ github.token }}
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.nodejs }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Start Redis
      uses: supercharge/redis-github-action@1.7.0
      with:
        redis-version: ${{ matrix.redis-version }}
    - run: yarn install --frozen-lockfile
    - run: yarn test
